version: "3.9"
services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oss
    ports:
      - ${DB_PORT:-5433}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:      
  