addSbtPlugin("de.gccc.sbt"           % "sbt-jib"             % "1.3.6")
addSbtPlugin("com.github.sbt"        % "sbt-dynver"          % "5.0.1")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("com.github.ghostdogpr" % "caliban-codegen-sbt" % "2.2.1")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"        % "0.11.0")
addSbtPlugin("io.spray"              % "sbt-revolver"        % "0.10.0")
